### ISSUE TITLE
Transition function

### ISSUE THREAD

**Issue by emapco** [emapco/CA-project#7]
The transition function is required to incorporate the chosen rule_type, boundary_type, and neighbor_type in order to update the cellular automata cells' state.

**Comment by emapco** [comment]
@TsukiTiger @trevoroldham 
design changes:
- we should make vector, matrix, and tensor private variables so that the user can't modify them
- we need duplicate vector, matrix, and tensor's for storing the updated state
- we need a private `steps_taken` variable to store the number of steps the CA simulation has taken
- `ndims` isn't actually need since we can check if vector, matrix, and tensor are nullptr
- I created a `Utils/` directory to store a utility functions (currently a `swap_states` function for swapping the current state and the next state).
- n, m, p aren't really descriptive. we should change them
  - I'm thinking maybe axis1_dim, axis2_dim, and axis3_dim but if you guys have different naming suggestion please comment them here.
- I'm currently working on our transition function. These are just issues I have come across will implementing the function.

**Comment by emapco** [comment]
I've pushed my changes to my branch if you want to pull and view it.

**Comment by trevoroldham** [comment]
These are all good points. I don't see the changes you made in the main branch, the latest version I see is the merge request # 7.

**Comment by trevoroldham** [comment]
I mean #8, from 20 hours ago

**Comment by emapco** [comment]
I haven't made a PR since this issue is still on going. I pushed my changes to the `Emmanuel` branch. You can `git pull origin Emmanuel` to view my code or [go to this link](https://github.com/emapco/CA-project/tree/Emmanuel) to view it on GH. I also just pushed my first iteration of the 1d-transistion state. I used the STL for some operations.

**Comment by emapco** [comment]
Resolved with PR #10.
